name: hhu_helper
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.3
  google_fonts: ^3.0.1
  camera: ^0.10.2+1
  path: ^1.8.2
  path_provider: ^2.0.12
  gallery_saver: ^2.3.2
  permission_handler: ^10.2.0
  spreadsheet_decoder: ^2.1.1
  syncfusion_flutter_xlsio: ^20.4.48-beta
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

